<a href="https://colab.research.google.com/github/Er-Yash/Based-on-Pre-Processing-in-Textual-Data/blob/main/Based_on_Pre_Processing_in_Textual_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Load a corpus (of .txt files) of your choice containing at least 10 text files using:
1. File method


In [ ]:
import os
filenames=os.listdir('/content/data_files')
contents=[]
for i in range(len(filenames)):
  f=open('/content/data_files/'+filenames[i],'r')
  text=f.read()
  contents.append(text)
  f.close()
print(contents)

['8 Biggest Graphic Design Trends For 2020 & Beyond [Infographic]\nAs you have probably noticed, the past few years in design have been dominated by bold colors, mind-bending gradients, and futuristic compositions. \n\nBut in 2020, the graphic design world is going to feel a lot more reserved, harmonious, and natural. \n\nWell, except for the illustrations, those are going to get a lot more abstract this year.\n\nThis shift is likely a reaction to the overuse of some of the previous graphic design trends. \n\nDesign styles that were very unique just a few years ago have become just another common tactic used by massive corporations. \n\nSo to stay ahead of the curve, be sure to check out the 8 Graphic Design Trends for 2020 and beyond below! ', 'Sorry I missed you Raymond, I was just out in Dahlgren last month...\nI\'m the Virtual Reality market manager for Silicon Graphics, so perhaps I\ncan help a little.\nIn article <1993Mar17.185725.13487@relay.nswc.navy.mil>,\nrchui@nswc-wo.nswc.n

Load a corpus (of .txt files) of your choice containing at least 10 text files using:

2. PlaintextCorpusReader

In [ ]:
from nltk.corpus import PlaintextCorpusReader
dataset=PlaintextCorpusReader('/content/data_files/','.*')
print(dataset)

<PlaintextCorpusReader in '/content/data_files'>


# **Pre-Processing Step 1: Normalization**

In [ ]:
lower_corpus = []
alpha_corpus = []

# Assuming 'contents' is a list of strings
for i in range(len(contents)):
    # Convert to lowercase
    lower_corpus.append(contents[i].lower())
# print(lower_corpus)

    # Keep only alphabetic characters and spaces
    alpha_corpus.append(' '.join([word for word in lower_corpus[i].split() if word.isalpha()]))
print(lower_corpus)
print(alpha_corpus)


['8 biggest graphic design trends for 2020 & beyond [infographic]\nas you have probably noticed, the past few years in design have been dominated by bold colors, mind-bending gradients, and futuristic compositions. \n\nbut in 2020, the graphic design world is going to feel a lot more reserved, harmonious, and natural. \n\nwell, except for the illustrations, those are going to get a lot more abstract this year.\n\nthis shift is likely a reaction to the overuse of some of the previous graphic design trends. \n\ndesign styles that were very unique just a few years ago have become just another common tactic used by massive corporations. \n\nso to stay ahead of the curve, be sure to check out the 8 graphic design trends for 2020 and beyond below! ', 'sorry i missed you raymond, i was just out in dahlgren last month...\ni\'m the virtual reality market manager for silicon graphics, so perhaps i\ncan help a little.\nin article <1993mar17.185725.13487@relay.nswc.navy.mil>,\nrchui@nswc-wo.nswc.n

# **Tokenization**

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
tokenized_corpus=[]
for i in range(len(alpha_corpus)):
  tokenized_corpus.append(word_tokenize(alpha_corpus[i]))
print(tokenized_corpus)

[['biggest', 'graphic', 'design', 'trends', 'for', 'beyond', 'as', 'you', 'have', 'probably', 'the', 'past', 'few', 'years', 'in', 'design', 'have', 'been', 'dominated', 'by', 'bold', 'and', 'futuristic', 'but', 'in', 'the', 'graphic', 'design', 'world', 'is', 'going', 'to', 'feel', 'a', 'lot', 'more', 'and', 'except', 'for', 'the', 'those', 'are', 'going', 'to', 'get', 'a', 'lot', 'more', 'abstract', 'this', 'this', 'shift', 'is', 'likely', 'a', 'reaction', 'to', 'the', 'overuse', 'of', 'some', 'of', 'the', 'previous', 'graphic', 'design', 'design', 'styles', 'that', 'were', 'very', 'unique', 'just', 'a', 'few', 'years', 'ago', 'have', 'become', 'just', 'another', 'common', 'tactic', 'used', 'by', 'massive', 'so', 'to', 'stay', 'ahead', 'of', 'the', 'be', 'sure', 'to', 'check', 'out', 'the', 'graphic', 'design', 'trends', 'for', 'and', 'beyond'], ['sorry', 'i', 'missed', 'you', 'i', 'was', 'just', 'out', 'in', 'dahlgren', 'last', 'the', 'virtual', 'reality', 'market', 'manager', 'for'

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


# **Removal Stopword**

In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
# stop=stopwords.words(fields='english')
tokenized_corpus_nostop=[]
for i in range(len(tokenized_corpus)):
  tokenized_corpus_nostop.append([word for word in tokenized_corpus[i] if word not in stop])
print(tokenized_corpus_nostop)

[]


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


# **Stemming**

In [ ]:
from nltk.stem import PorterStemmer
ps=PorterStemmer()
tokenized_corpus_nostop_stem=[]
for i in range(len(tokenized_corpus_nostop)):
  tokenized_corpus_nostop_stem.append([ps.stem(word) for word in tokenized_corpus_nostop[i]])
print(tokenized_corpus_nostop_stem)

[]


# ***Convert the corpus into Bag-of-Words and tf-idf feature matrix using:***
(a) TfidfVectorizer()and CountVectorizer

(b) Without using in-built functions

In [ ]:
!pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

corpus=alpha_corpus

count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(corpus)

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(corpus)

X_count_dense = X_count.toarray()
X_tfidf_dense = X_tfidf.toarray()

print("Bag-of-Words Feature Matrix:")
print(X_count_dense)
print("\nTF-IDF Feature Matrix:")
print(X_tfidf_dense)

print("\nFeature Names:")
print("Bag-of-Words:", count_vectorizer.get_feature_names_out())
print("TF-IDF:", tfidf_vectorizer.get_feature_names_out())


Bag-of-Words Feature Matrix:
[[0 0 0 ... 2 1 0]
 [1 0 2 ... 0 4 1]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 4 3]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

TF-IDF Feature Matrix:
[[0.         0.         0.         ... 0.19759352 0.04973759 0.        ]
 [0.02653185 0.         0.04535692 ... 0.         0.05342808 0.01609104]
 [0.         0.         0.         ... 0.         0.03220846 0.        ]
 ...
 [0.         0.         0.         ... 0.         0.14994254 0.1354755 ]
 [0.         0.12098996 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]

Feature Names:
Bag-of-Words: ['abc' 'ability' 'able' 'about' 'above' 'abstract' 'accelerated' 'access'
 'according' 'accurate' 'acheive' 'actual' 'actually' 'add' 'addresses'
 'admit' 'adobe' 'ads' 'advanced' 'after' 'agency' 'ago' 'agrees' 'ahead'
 'albeit' 'aliased' 'all' 'allen' 'almost' 'aload' 'also' 'am' 'amro'
 'amusement' 'an' 'and' 'animation' 'another' 'answer' 'ant' 'a

In [ ]:
import numpy as np

def create_bow(corpus):
    unique_words = list(set(word for sentence in corpus for word in sentence.split()))
    bow_matrix = np.zeros((len(corpus), len(unique_words)))

    for i, sentence in enumerate(corpus):
        for word in sentence.split():
            bow_matrix[i, unique_words.index(word)] += 1

    return bow_matrix, unique_words

corpus = alpha_corpus


X_bow, unique_words = create_bow(corpus)

print("Bag-of-Words Feature Matrix:")
print(X_bow)
print("\nUnique Words:", unique_words)


Bag-of-Words Feature Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 2. ... 0. 1. 4.]
 [1. 0. 0. ... 0. 2. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Unique Words: ['length', 'hp', 'due', 'constant', 'monthly', 'humor', 'game', 'like', 'pages', 'addresses', 'same', 'coworkers', 'except', 'tools', 'fully', 'make', 'interlaced', 'hill', 'develop', 'displays', 'whether', 'local', 'using', 'comments', 'distraction', 'currently', 'until', 'include', 'corp', 'making', 'simpler', 'step', 'kubota', 'so', 'graphic', 'ago', 'abstract', 'philip', 'canada', 'recommed', 'require', 'reading', 'wanting', 'phong', 'tom', 'online', 'immersed', 'apply', 'monitor', 'very', 'line', 'environments', 'streamline', 'sleek', 'curve', 'still', 'graphics', 'contact', 'press', 'anywhere', 'these', 'feel', 'ideas', 'carmack', 'i', 'critique', 'flyers', 'buggy', 'cards', 'packages', 'dominic', 'newly', 'onyx', 'video', 'art', 'being', 'going', 'techniques', 'robust', 'five', 'coo

In [ ]:
def calculate_tf(word, sentence):
    return sentence.split().count(word) / len(sentence.split())

def calculate_idf(word, corpus):
    num_documents_with_word = sum(1 for doc in corpus if word in doc.split())
    return np.log(len(corpus) / (1 + num_documents_with_word))

def create_tfidf(corpus):
    unique_words = list(set(word for sentence in corpus for word in sentence.split()))
    tfidf_matrix = np.zeros((len(corpus), len(unique_words)))

    for i, sentence in enumerate(corpus):
        for j, word in enumerate(unique_words):
            tf = calculate_tf(word, sentence)
            idf = calculate_idf(word, corpus)
            tfidf_matrix[i, j] = tf * idf

    return tfidf_matrix, unique_words

X_tfidf, unique_words_tfidf = create_tfidf(corpus)

print("\nTF-IDF Feature Matrix:")
print(X_tfidf)
print("\nUnique Words for TF-IDF:", unique_words_tfidf)



TF-IDF Feature Matrix:
[[ 0.         -0.04462871  0.          0.05753641  0.          0.
   0.          0.          0.          0.          0.05753641  0.
   0.05753641]
 [ 0.         -0.03719059  0.          0.          0.          0.
   0.11552453  0.11552453  0.          0.          0.04794701  0.
   0.04794701]
 [ 0.         -0.03719059  0.04794701  0.          0.          0.11552453
   0.          0.          0.11552453  0.11552453  0.          0.
   0.        ]
 [ 0.13862944 -0.04462871  0.05753641  0.05753641  0.13862944  0.
   0.          0.          0.          0.          0.          0.
   0.        ]]

Unique Words for TF-IDF: ['Is', 'the', 'this', 'first', 'document?', 'And', 'second', 'document', 'one.', 'third', 'document.', 'is', 'This']


# ***Without using in-built functions***

In [ ]:
import re
import math
from collections import Counter

def preprocess_text(text):

    clean_text = re.sub('<.*?>', '', text)

    clean_text = re.sub(r'[^a-zA-Z0-9\s]', '', clean_text.lower())
    return clean_text

def tokenize(text):

    return text.split()

def create_bow(corpus):

    bow_matrix = []

    for document in corpus:

        preprocessed_doc = preprocess_text(document)

        tokens = tokenize(preprocessed_doc)

        document_bow = Counter(tokens)

        bow_matrix.append(document_bow)

    return bow_matrix

def calculate_tf(term, document):

    term_count = document[term]
    total_terms = sum(document.values())
    return term_count / total_terms

def create_tf_idf(corpus, bow_matrix):

    idf_values = {}
    num_documents = len(corpus)

    for document_bow in bow_matrix:
        for term in document_bow:
            idf_values[term] = idf_values.get(term, 0) + 1

    for term, idf in idf_values.items():
        idf_values[term] = math.log(num_documents / (1 + idf))


    tf_idf_matrix = []

    for document_bow in bow_matrix:
        tf_idf_vector = {}

        for term in document_bow:
            tf = calculate_tf(term, document_bow)
            idf = idf_values[term]
            tf_idf_vector[term] = tf * idf

        tf_idf_matrix.append(tf_idf_vector)

    return tf_idf_matrix

corpus = alpha_corpus

bow_matrix = create_bow(corpus)


print("Bag-of-Words Matrix:")
for i, document_bow in enumerate(bow_matrix):
    print(f"Document {i+1}: {document_bow}")

tf_idf_matrix = create_tf_idf(corpus, bow_matrix)

print("\nTF-IDF Matrix:")
for i, tf_idf_vector in enumerate(tf_idf_matrix):
    print(f"Document {i+1}: {tf_idf_vector}")


Bag-of-Words Matrix:
Document 1: Counter({'the': 7, 'design': 6, 'to': 5, 'graphic': 4, 'a': 4, 'for': 3, 'have': 3, 'and': 3, 'of': 3, 'trends': 2, 'beyond': 2, 'few': 2, 'years': 2, 'in': 2, 'by': 2, 'is': 2, 'going': 2, 'lot': 2, 'more': 2, 'this': 2, 'just': 2, 'biggest': 1, 'as': 1, 'you': 1, 'probably': 1, 'past': 1, 'been': 1, 'dominated': 1, 'bold': 1, 'futuristic': 1, 'but': 1, 'world': 1, 'feel': 1, 'except': 1, 'those': 1, 'are': 1, 'get': 1, 'abstract': 1, 'shift': 1, 'likely': 1, 'reaction': 1, 'overuse': 1, 'some': 1, 'previous': 1, 'styles': 1, 'that': 1, 'were': 1, 'very': 1, 'unique': 1, 'ago': 1, 'become': 1, 'another': 1, 'common': 1, 'tactic': 1, 'used': 1, 'massive': 1, 'so': 1, 'stay': 1, 'ahead': 1, 'be': 1, 'sure': 1, 'check': 1, 'out': 1})
Document 2: Counter({'the': 37, 'to': 19, 'graphics': 14, 'of': 14, 'and': 13, 'are': 11, 'virtual': 10, 'a': 10, 'in': 9, 'systems': 9, 'not': 8, 'vr': 8, 'for': 7, 'is': 7, 'frame': 6, 'support': 6, 'reality': 5, 'we': 5, '

# ***access HTML TEXT***

In [ ]:
!pip install beautifulsoup4
from bs4 import BeautifulSoup
import requests
url="https://example.com"
response=requests.get(url)
html_content=response.text
soup=BeautifulSoup(html_content,'html.parser')
t=soup.title.text
print("Title:",t)
para=soup.find_all('p')
for paragraph in para:
  print(paragraph.text)

Title: Example Domain
This domain is for use in illustrative examples in documents. You may use this
    domain in literature without prior coordination or asking for permission.
More information...


# ***pre-process HTML TEXT***

In [ ]:
from bs4 import BeautifulSoup
import requests
import re

url = "https://example.com"

response = requests.get(url)
html_content = response.text

soup = BeautifulSoup(html_content, 'html.parser')

text_content = soup.get_text()

text_content = re.sub(r'\s+', ' ', text_content).strip()

text_content = text_content.lower()

print("Processed Text:")
print(text_content)


Processed Text:
example domain example domain this domain is for use in illustrative examples in documents. you may use this domain in literature without prior coordination or asking for permission. more information...


# ***create feature vector for HTML texts***

In [ ]:
from bs4 import BeautifulSoup
from sklearn.feature_extraction.text import CountVectorizer

html_text = text_content

def extract_text_from_html(html):
    soup = BeautifulSoup(html, 'html.parser')
    return soup.get_text()

text = extract_text_from_html(html_text)

vectorizer = CountVectorizer()

feature_vector = vectorizer.fit_transform([text])

feature_array = feature_vector.toarray()

print("Feature Vector:")
print(feature_array)


Feature Vector:
[[1 1 1 4 2 1 2 1 3 1 1 1 1 1 1 1 1 2 2 1 1]]
